langs_dict = {
    "door-open": "open a door with a revolving joint",
    "drawer-open": "open a drawer",
    "drawer-close": "push and close a drawer",
    "window-open": "push and open a window",
    "window-close": "push and close a window",
    "button-press-topdown": "press the button from the top",
    
    "assembly": "pick up a nut and place it onto a peg",
    "basketball": "dunk the basketball into the basket",
    "bin-picking": "grasp the puck from one bin and place it into another bin",
    "box-close": "grasp the cover and close the box with it",
    "button-press-topdown-wall": "bypass a wall and press a button from the top",
    "button-press": "press a button",
    "button-press-wall": "bypass a wall and press a button",
    "coffee-button": "push a button on the coffee machine",
    "coffee-pull": "pull a mug from a coffee machine",
    "coffee-push": "push a mug under a coffee machine",
    "dial-turn": "rotate a dial 180 degrees",
    "disassemble": "pick a nut out of a peg",

    "door-close": "close a door with a revolving joint",
    "door-lock": "lock the door by rotating the lock clockwise",
    "door-unlock": "unlock the door by rotating the lock counter-clockwise",
    "hand-insert": "insert the gripper into a hole",
    "faucet-open": "rotate the faucet counter-clockwise to turn on it",
    "faucet-close": "rotate the faucet clockwise to turn off it",
    "hammer": "hammer a screw on the wall",
    "reach": "reach the goal point",
    "push": "push the puck to the goal point",
    "pick-place": "pick and place a puck to the goal point",
    "peg-insert-side": "insert a peg sideways to the goal point",
}

dict_56_88 = {
    "coffee-push": "push a mug under a coffee machine",
    "push": "push the puck to the goal",
    "pick-place": "pick and place a puck to the goal",
    "button-press-topdown": "press the button from the top",
    "door-close": "close a door with a revolving joint",
    "faucet-close": "rotate the faucet clockwise to turn off it",
    "button-press-wall": "bypass a wall and press a button",
    "hammer": "hammer a screw on the wall",
    "drawer-close": "push and close a drawer",
    "button-press-topdown-wall": "bypass a wall and press a button from the top",
    "coffee-pull": "pull a mug from a coffee machine",
    "dial-turn": "rotate a dial 180 degrees",
    "button-press": "press a button",
    "window-close": "push and close a window",
    "drawer-open": "open a drawer",
    "window-open": "push and open a window",
    "door-open": "open a door with a revolving joint",
    "assembly": "pick up a nut and place it onto a peg",

    "pick-place-wall": "pick a puck, bypass a wall and place the puck",
    "peg-unplug-side": "unplug a peg sideways",
    "push-wall": "bypass a wall and push a puck to the goal",
    "stick-push": "grasp a stick and push a box using the stick",
    "sweep": "sweep a puck off the table",
    "plate-slide-side": "slide a plate into a cabinet sideways",
    "push-back": "pull a puck to the goal",
    "lever-pull": "pull a lever down 90 degrees",
    "plate-slide-back": "get a plate from the cabinet",
    "shelf-place": "pick and place a puck onto a shelf",
    "handle-pull-side": "pull a handle up sideways",
    "stick-pull": "grasp a stick and pull a box with the stick",
}

# task_list = {  # MT10
#     "window-close": "push and close a window",
#     "window-open": "push and open a window",
#     "door-open": "open a door with a revolving joint",
#     "peg-insert-side": "insert a peg sideways to the goal point",
#     "drawer-open": "open a drawer",
#     "pick-place": "pick a puck, and place the puck to the goal",
#     "reach": "reach the goal point",
#     "button-press-topdown": "press the button from the top",
#     "push": "push the puck to the goal point",
#     "drawer-close": "push and close a drawer",
# }

task_list = {  # ML10
    "peg-insert-side": "insert a peg sideways to the goal point",
    "reach": "reach the goal point",
    "door-open": "open a door with a revolving joint",
    "basketball": "pick the basketball, and place it into the basket",
    "window-open": "push and open a window",
    "pick-place": "pick a puck, and place the puck to the goal",
    "button-press-topdown": "press the button from the top",
    "push": "push the puck to the goal point",
    "drawer-close": "push and close a drawer",
    "sweep": "sweep a puck off the table",

    ## Test
    "door-close": "close a door with a revolving joint",
    "shelf-place": "pick a puck, and place the puck onto a shelf",
    "drawer-open": "open a drawer",
    "sweep-into": "sweep a puck into a box",
    "lever-pull": "pull a lever down 90 degrees",
}


# task_list = {
#     "assembly": "pick up a ring and place it onto a peg",
#     # "bin-picking": "pick and place a block between bins",
#     "button-press": "push a button",
#     "drawer-open": "open a drawer",
#     "hammer": "hammer a nail on the wall",
#
#     "window-close": "push and close a window",
#     "pick-place-wall": "pick a puck, bypass a wall and place the puck",
#     "faucet-close": "rotate the faucet clockwise to turn off it",
#     "push-wall": "bypass a wall and push a puck to the goal",
# }


task_list_orig = {
    "assembly": "assembling a ring onto a peg",
    "bin-picking": "pick and place a block between bins",
    "button-press": "push a button",
    "drawer-open": "open a drawer",
    # "window-close": "close a window",
    "hammer": "hammer a nail",
    "window-open": "open a window",
    "drawer-close": "close a drawer",
}

METAWORLD_EVAL_INSTRS = {
    #
    # 'drawer-close': {'seen': ['push and close a drawer'],
    #                  'unseen verb': ['shut drawer'],
    #                  'unseen noun': ['close container'],
    #                  'unseen verb noun': ['shut container'],
    #                  'human': ['push the drawer shut',
    #                            'draw the drawer closed',
    #                            'shut the drawer',
    #                            'push drawer',
    #                            'slide the drawer closed',
    #                            'push and shut the drawer',
    #                            'shut the dresser',
    #                            'shut the drawer.',
    #                            'shut the cupboard']},
    'drawer-open': {'seen': ['open a drawer'],
                    'unseen verb': ['pull drawer'],
                    'unseen noun': ['open container'],
                    'unseen verb noun': ['pull container'],
                    'human': ['pull the drawer open',
                              'pull the handle',
                              'pull the drawer handle',
                              'pull the drawer open',
                              'pull open the drawer',
                              'open the dresser',
                              'pull the drawer',
                              'unclose the cabinet']},
    # 'window-close': {'seen': ['push and close a window'],
    #                      'unseen verb': ['push and shut window'],
    #                      'unseen noun': ['push and close pane'],
    #                      'unseen verb noun': ['push and shut pane'],
    #                      'human': ['push the window shut',
    #                                'push the window',
    #                                'draw the window closed',
    #                                'shut window',
    #                                'slide the window closed',
    #                                'shut the window',
    #                                'shut the glazing',
    #                                'push and shut the window.',
    #                                'seal the opening']},
    'faucet-close': {'seen': ['rotate the faucet clockwise to turn off it'],
                          'unseen verb': ['turn the faucet clockwise to turn off it'],
                          'unseen noun': ['rotate the tap clockwise to turn off it'],
                          'unseen verb noun': ['turn the tap clockwise to turn off it'],
                          'human': ['turn faucet right-handwise',
                                    'rotate faucet towards camera',
                                    'turn nozzle clockwise',
                                    'faucet right-handwise',
                                    'turn the faucet clockwise',
                                    # 'rotate the faucet right-handwise',
                                    'turn handle rightward',
                                    'rotate faucet right-handwise',
                                    'twirl valve clockwise']},
    'coffee-push': {'seen': ['push a mug under a coffee machine'],
                             'unseen verb': ['move a mug under a coffee machine'],
                             'unseen noun': ['push a cup under a coffee machine'],
                             'unseen verb noun': ['move a cup under a coffee machine'],
                             'human': ['translate the mug below a coffee maker',
                                       'reposition the cup beneath a coffee machine',
                                       'move the mug under a coffee maker',
                                       'the mug under a coffee machine',
                                       'slide the cup under a coffee machine',
                                       'push the cup to beneath a coffee machine',
                                       'move the mug below a coffee maker',
                                       'push the mug below a coffee machine.',
                                       'shift the cup under a coffee machine']},
    # 'coffee-pull': {'seen': ['pull a mug from a coffee machine'],
    #                         'unseen verb': ['move a mug from a coffee machine'],
    #                         'unseen noun': ['pull a cup from a coffee machine'],
    #                         'unseen verb noun': ['move a cup from a coffee machine'],
    #                         'human': ['translate the mug away from a coffee machine',
    #                                   # 'pull the cup closer to the faucet',
    #                                   'bring a mug from a coffee maker',
    #                                   'cup from a coffee machine',
    #                                   'move the cup up and left',
    #                                   'pull the cup from a coffee maker',
    #                                   'shift the cup away from a coffee machine',
    #                                   'distance the cup from a coffee maker.',
    #                                   'reposition a glass away from a coffee machine']},
}