# @package _global_

learning_rate: 1e-5
lm_learning_rate: 1e-7
weight_decay: 1e-4
os_learning_rate: 1e-6  # 1e-5

env:
  name: LorlEnv-v0
  state_dim: (3, 64, 64)
  action_dim: 5
  discrete: False
  eval_offline: False
  use_state: False
  eval_episode_factor: 10  # 10
  eval_env: 

train_dataset:
  expert_location: '/path/to/prep_data.pkl'
  num_trajectories: 40108
  normalize_states: False
  no_lang: False
  seed: ${seed}
  aug: True

val_dataset:
  expert_location: 
  num_trajectories: ${trainer.num_eval_episodes}
  normalize_states: False
  seed: ${seed}
  aug: True


trainer:
  device:  ## to be filled in code
  state_il: False
  num_eval_episodes: 5  # 5
  eval_every: 20
  K: ${model.K}